file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/bcm2835.h" ver)

string(REGEX MATCH "BCM2835_VERSION ([0-9]*)00([0-9]*)" _ ${ver})

set(VERSION_MAJOR ${CMAKE_MATCH_1})
set(VERSION_MINOR ${CMAKE_MATCH_2})

set(VERSION ${VERSION_MAJOR}.${VERSION_MINOR})