name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Update
        id: run_update
        run: bash ${GITHUB_WORKSPACE}/update.sh
      - name: Create branch
        if: ${{ steps.run_update.outputs.updated == '1' }}
        run: |
          git --version
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git checkout -b update-${{ steps.run_update.outputs.version }}
          git add --all
          git commit -m "[ci] auto-update to ${{ steps.run_update.outputs.version }}"
          git push origin update-${{ steps.run_update.outputs.version }}
      - name: Create Pull Request
        uses: actions/github-script@v6
        if: ${{ steps.run_update.outputs.updated == '1' }}
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Source code update',
              owner,
              repo,
              head: 'update-${{ steps.run_update.outputs.version }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });